controller_list:
  - name: arm/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5