## joint_names
joint_names: [arm_joint1, arm_joint2, arm_joint3, arm_joint4, arm_joint5, arm_joint6]

## control_mode_adapter
max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## joint trajectory controller
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - arm_joint1
     - arm_joint2
     - arm_joint3
     - arm_joint4
     - arm_joint5
     - arm_joint6
  constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.05
      arm_joint1: {trajectory: 0.1, goal: 0.1}
      arm_joint2: {trajectory: 0.1, goal: 0.1}
      arm_joint3: {trajectory: 0.1, goal: 0.1}
      arm_joint4: {trajectory: 0.1, goal: 0.1}
      arm_joint5: {trajectory: 0.1, goal: 0.1}
      arm_joint6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

## position controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - arm_joint1
     - arm_joint2
     - arm_joint3
     - arm_joint4
     - arm_joint5
     - arm_joint6

arm_joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint1
arm_joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint2
arm_joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint3
arm_joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint4
arm_joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint5
arm_joint6_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint6

## velocity controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - arm_joint1
     - arm_joint2
     - arm_joint3
     - arm_joint4
     - arm_joint5
     - arm_joint6

arm_joint1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_joint1
arm_joint2_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_joint2
arm_joint3_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_joint3
arm_joint4_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_joint4
arm_joint5_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_joint5
arm_joint6_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: arm_joint6

## no further controllers available
